from django.urls import path
from . import views
urlpatterns = [
    path('',views.index, name="index"),
    path('add-billing.html',views.addbilling, name="addbilling"),
    path('add-prescription.html',views.addprescription, name="addprescription"),
    path('appointments.html',views.appointments,name="appointments"),
    path('blank-page.html',views.blankpage, name="blankpage"),
    path('booking.html',views.booking, name="booking"),
    path('booking-success.html',views.bookingsuccess, name="bookingsuccess"),
    path('calendar.html',views.calender, name="calender"),
    path('change-password.html',views.changepassword, name="changepassword"),
    path('chat.html',views.chat, name="chat"),
    path('chat-doctor.html',views.chatdoctor, name="chatdoctor"),
    path('checkout.html',views.checkout, name="checkout"),
    path('components.html',views.components, name="components"),
    path('doctor-change-password.html',views.doctorchangepassword, name="doctorchangepassword"),
    path('doctor-dashboard.html',views.doctordashboard, name="doctordashboard"),
    path('doctor-profile.html',views.doctorprofile, name="doctorprofile"),
    path('doctor-profile-settings.html',views.doctorprofilesettings, name="doctorprofilesettings"),
    path('doctor-register.html',views.doctorregister, name="doctorregister"),
    path('edit-billing.html',views.editbilling, name="editbilling"),
    path('edit-prescription.html',views.editprescription, name="editprescription"),
    path('favorites.html',views.favorites, name="favorites"),
    path('forgot-password.html',views.forgotpassword, name="forgotpassword"),
    path('index-2.html',views.index2, name="index2"),
    path('invoice-view.html',views.invoiceview, name="invoiceview"),
    path('invoices.html',views.invoices, name="invoices"),
    path('login.html',views.login,name="login"),
    path('my-patients.html',views.mypatients, name="mypatients"),
    path('patient-dashboard.html',views.patientdashboard, name="patientdashboard"),
    path('patient-profile.html',views.patientprofile, name="patientprofile"),
    path('privacy-policy.html',views.privacypolicy, name="privacypolicy"),
    path('profile-settings.html',views.profilesettings, name="profilesettings"),
    path('register.html',views.register, name="register"),
    path('reviews.html',views.reviews, name="reviews"),
    path('schedule-timings.html',views.scheduletimings, name="scheduletimings"),
    path('search.html',views.search, name="search"),
    path('social-media.html',views.socialmedia, name="socialmedia"),
    path('term-condition.html',views.termcondition, name="termcondition"),
    path('video-call.html',views.videocall, name="videocall"),
    path('voice-call.html',views.voicecall, name="voicecall"),
    

]