# Generated by Django 4.0.5 on 2022-07-23 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('blodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentonblog', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('blogname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.blogs')),
                ('commentatorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
