# Generated by Django 4.0.5 on 2022-06-05 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_appointment_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recomend', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=360)),
                ('doctorratingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.doctor_profile')),
                ('patientratingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patient_profile')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.CharField(choices=[('9:30 - 10:30', '9:30 - 10:30'), ('10:30 - 11:30', '10:30 - 11:30'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 1:30', '12:30 - 1:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')], max_length=50)),
                ('schedule_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('schedule_doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.doctor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=20)),
                ('doctor_reply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.doctor_profile')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.rating')),
            ],
        ),
    ]
