# Generated by Django 4.0.4 on 2022-05-16 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
