# Generated by Django 4.0.4 on 2022-05-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='admin',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='admin',
            new_name='patient',
        ),
    ]
