# Generated by Django 4.0.4 on 2022-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_appointment_booking_doctor_profile_patient_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='clinic_images',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='patient_profile',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
