# Generated by Django 4.0.4 on 2022-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctormobilenumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctormobilenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patientmobilenumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientmobilenumber', models.IntegerField()),
            ],
        ),
    ]
