# Generated by Django 4.0.4 on 2022-05-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_doctor_profile_clinic_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_booking',
            name='Payment_card',
            field=models.CharField(max_length=50),
        ),
    ]
