# Generated by Django 4.0.4 on 2022-05-18 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_appointment_booking_payment_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patient_profile',
            name='image',
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='doctor_images',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_profile',
            name='patient_images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='clinic_images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
