# Generated by Django 4.0.4 on 2022-05-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_doctormobilenumber_patientmobilenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctormobilenumber',
        ),
        migrations.DeleteModel(
            name='patientmobilenumber',
        ),
    ]
