# Generated by Django 4.0.4 on 2022-05-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_rename_admin_doctor_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin',
            new_name='Admin',
        ),
    ]
